# id: 1
orchestrator:
  address: "orchestrator:12345"
loop:
  amount: 5
  period: "5s"
log:
  level: "info"
output:
  baseDir: "/client_runs"
batch:
  maxAmount: 50000 # number of lines
data:
  folder: "/data" # folder with CSV files
retries:
  attempts: 5
  retryInterval: 2 # in seconds
time:
  timeAfterProcessing: "600s" #Time to wait after processing all files before shutting down the client
