# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eof_message.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'eof_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import table_data_pb2 as table__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65of_message.proto\x12\x08protocol\x1a\x10table_data.proto\"R\n\nEOFMessage\x12\"\n\x05table\x18\x01 \x01(\x0e\x32\x13.protocol.TableName\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\r\n\x05trace\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eof_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EOFMESSAGE']._serialized_start=49
  _globals['_EOFMESSAGE']._serialized_end=131
# @@protoc_insertion_point(module_scope)
