# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: databatch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'databatch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import table_data_pb2 as table__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61tabatch.proto\x12\x08protocol\x1a\x10table_data.proto\"\xbc\x01\n\tDataBatch\x12\"\n\tquery_ids\x18\x01 \x03(\x0e\x32\x0f.protocol.Query\x12\x14\n\x0ctotal_copies\x18\x02 \x01(\x05\x12\x10\n\x08\x63opy_num\x18\x03 \x01(\x05\x12\x14\n\x0ctotal_shards\x18\x04 \x01(\x05\x12\x11\n\tshard_num\x18\x05 \x01(\x05\x12\x14\n\x0c\x66ilter_steps\x18\x06 \x01(\x05\x12$\n\x07payload\x18\x07 \x01(\x0b\x32\x13.protocol.TableData*\'\n\x05Query\x12\x06\n\x02Q1\x10\x00\x12\x06\n\x02Q2\x10\x01\x12\x06\n\x02Q3\x10\x02\x12\x06\n\x02Q4\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'databatch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERY']._serialized_start=238
  _globals['_QUERY']._serialized_end=277
  _globals['_DATABATCH']._serialized_start=48
  _globals['_DATABATCH']._serialized_end=236
# @@protoc_insertion_point(module_scope)
