# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'query_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13query_request.proto\x12\x08protocol\"7\n\x0cQueryRequest\x12\'\n\nquery_type\x18\x01 \x01(\x0e\x32\x13.protocol.QueryType*?\n\tQueryType\x12\x0b\n\x07QUERY_1\x10\x00\x12\x0b\n\x07QUERY_2\x10\x01\x12\x0b\n\x07QUERY_3\x10\x02\x12\x0b\n\x07QUERY_4\x10\x03\x42\x36Z4github.com/fede/coffee-shop-analyzer/protos;protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/fede/coffee-shop-analyzer/protos;protocol'
  _globals['_QUERYTYPE']._serialized_start=90
  _globals['_QUERYTYPE']._serialized_end=153
  _globals['_QUERYREQUEST']._serialized_start=33
  _globals['_QUERYREQUEST']._serialized_end=88
# @@protoc_insertion_point(module_scope)
