# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: table_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'table_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10table_data.proto\x12\x08protocol\"\x1e\n\x0bTableSchema\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\t\"\x15\n\x03Row\x12\x0e\n\x06values\x18\x01 \x03(\t\"\xaf\x01\n\tTableData\x12!\n\x04name\x18\x01 \x01(\x0e\x32\x13.protocol.TableName\x12%\n\x06schema\x18\x02 \x01(\x0b\x32\x15.protocol.TableSchema\x12\x1b\n\x04rows\x18\x03 \x03(\x0b\x32\r.protocol.Row\x12\x14\n\x0c\x62\x61tch_number\x18\x04 \x01(\x04\x12%\n\x06status\x18\x05 \x01(\x0e\x32\x15.protocol.BatchStatus*\xaf\x01\n\tTableName\x12\x0e\n\nMENU_ITEMS\x10\x00\x12\n\n\x06STORES\x10\x01\x12\x15\n\x11TRANSACTION_ITEMS\x10\x02\x12\x10\n\x0cTRANSACTIONS\x10\x03\x12\t\n\x05USERS\x10\x04\x12\x13\n\x0fQUERY_RESULTS_1\x10\x05\x12\x13\n\x0fQUERY_RESULTS_2\x10\x06\x12\x13\n\x0fQUERY_RESULTS_3\x10\x07\x12\x13\n\x0fQUERY_RESULTS_4\x10\x08*0\n\x0b\x42\x61tchStatus\x12\x0c\n\x08\x43ONTINUE\x10\x00\x12\x07\n\x03\x45OF\x10\x01\x12\n\n\x06\x43\x41NCEL\x10\x02\x42\x36Z4github.com/fede/coffee-shop-analyzer/protos;protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'table_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/fede/coffee-shop-analyzer/protos;protocol'
  _globals['_TABLENAME']._serialized_start=264
  _globals['_TABLENAME']._serialized_end=439
  _globals['_BATCHSTATUS']._serialized_start=441
  _globals['_BATCHSTATUS']._serialized_end=489
  _globals['_TABLESCHEMA']._serialized_start=30
  _globals['_TABLESCHEMA']._serialized_end=60
  _globals['_ROW']._serialized_start=62
  _globals['_ROW']._serialized_end=83
  _globals['_TABLEDATA']._serialized_start=86
  _globals['_TABLEDATA']._serialized_end=261
# @@protoc_insertion_point(module_scope)
