// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: envelope.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope_Opcode int32

const (
	Envelope_UNKNOWN            Envelope_Opcode = 0
	Envelope_EOF                Envelope_Opcode = 1
	Envelope_FINISHED           Envelope_Opcode = 2
	Envelope_TABLE_DATA         Envelope_Opcode = 3
	Envelope_BATCH_RECV_SUrCESS Envelope_Opcode = 4
	Envelope_BATCH_RECV_FAIL    Envelope_Opcode = 5
	Envelope_QUERY_REQUEST      Envelope_Opcode = 6
)

// Enum value maps for Envelope_Opcode.
var (
	Envelope_Opcode_name = map[int32]string{
		0: "UNKNOWN",
		1: "EOF",
		2: "FINISHED",
		3: "TABLE_DATA",
		4: "BATCH_RECV_SUrCESS",
		5: "BATCH_RECV_FAIL",
		6: "QUERY_REQUEST",
	}
	Envelope_Opcode_value = map[string]int32{
		"UNKNOWN":            0,
		"EOF":                1,
		"FINISHED":           2,
		"TABLE_DATA":         3,
		"BATCH_RECV_SUrCESS": 4,
		"BATCH_RECV_FAIL":    5,
		"QUERY_REQUEST":      6,
	}
)

func (x Envelope_Opcode) Enum() *Envelope_Opcode {
	p := new(Envelope_Opcode)
	*p = x
	return p
}

func (x Envelope_Opcode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Envelope_Opcode) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (Envelope_Opcode) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x Envelope_Opcode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Envelope_Opcode.Descriptor instead.
func (Envelope_Opcode) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0, 0}
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Envelope_Opcode        `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.Envelope_Opcode" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Eof
	//	*Envelope_TableData
	//	*Envelope_QueryRequest
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() Envelope_Opcode {
	if x != nil {
		return x.Type
	}
	return Envelope_UNKNOWN
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetEof() *EOFMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Eof); ok {
			return x.Eof
		}
	}
	return nil
}

func (x *Envelope) GetTableData() *TableData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TableData); ok {
			return x.TableData
		}
	}
	return nil
}

func (x *Envelope) GetQueryRequest() *QueryRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_QueryRequest); ok {
			return x.QueryRequest
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Eof struct {
	Eof *EOFMessage `protobuf:"bytes,2,opt,name=eof,proto3,oneof"`
}

type Envelope_TableData struct {
	TableData *TableData `protobuf:"bytes,3,opt,name=table_data,json=tableData,proto3,oneof"`
}

type Envelope_QueryRequest struct {
	QueryRequest *QueryRequest `protobuf:"bytes,4,opt,name=query_request,json=queryRequest,proto3,oneof"`
}

func (*Envelope_Eof) isEnvelope_Payload() {}

func (*Envelope_TableData) isEnvelope_Payload() {}

func (*Envelope_QueryRequest) isEnvelope_Payload() {}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\bprotocol\x1a\x11eof_message.proto\x1a\x10table_data.proto\x1a\x13query_request.proto\"\xe1\x02\n" +
	"\bEnvelope\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.protocol.Envelope.OpcodeR\x04type\x12(\n" +
	"\x03eof\x18\x02 \x01(\v2\x14.protocol.EOFMessageH\x00R\x03eof\x124\n" +
	"\n" +
	"table_data\x18\x03 \x01(\v2\x13.protocol.TableDataH\x00R\ttableData\x12=\n" +
	"\rquery_request\x18\x04 \x01(\v2\x16.protocol.QueryRequestH\x00R\fqueryRequest\"|\n" +
	"\x06Opcode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03EOF\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02\x12\x0e\n" +
	"\n" +
	"TABLE_DATA\x10\x03\x12\x16\n" +
	"\x12BATCH_RECV_SUrCESS\x10\x04\x12\x13\n" +
	"\x0fBATCH_RECV_FAIL\x10\x05\x12\x11\n" +
	"\rQUERY_REQUEST\x10\x06B\t\n" +
	"\apayloadB6Z4github.com/fede/coffee-shop-analyzer/protos;protocolb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envelope_proto_goTypes = []any{
	(Envelope_Opcode)(0), // 0: protocol.Envelope.Opcode
	(*Envelope)(nil),     // 1: protocol.Envelope
	(*EOFMessage)(nil),   // 2: protocol.EOFMessage
	(*TableData)(nil),    // 3: protocol.TableData
	(*QueryRequest)(nil), // 4: protocol.QueryRequest
}
var file_envelope_proto_depIdxs = []int32{
	0, // 0: protocol.Envelope.type:type_name -> protocol.Envelope.Opcode
	2, // 1: protocol.Envelope.eof:type_name -> protocol.EOFMessage
	3, // 2: protocol.Envelope.table_data:type_name -> protocol.TableData
	4, // 3: protocol.Envelope.query_request:type_name -> protocol.QueryRequest
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	file_eof_message_proto_init()
	file_table_data_proto_init()
	file_query_request_proto_init()
	file_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Eof)(nil),
		(*Envelope_TableData)(nil),
		(*Envelope_QueryRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
