// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: eof_message.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EOFMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         TableName              `protobuf:"varint,1,opt,name=table,proto3,enum=protocol.TableName" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EOFMessage) Reset() {
	*x = EOFMessage{}
	mi := &file_eof_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EOFMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EOFMessage) ProtoMessage() {}

func (x *EOFMessage) ProtoReflect() protoreflect.Message {
	mi := &file_eof_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EOFMessage.ProtoReflect.Descriptor instead.
func (*EOFMessage) Descriptor() ([]byte, []int) {
	return file_eof_message_proto_rawDescGZIP(), []int{0}
}

func (x *EOFMessage) GetTable() TableName {
	if x != nil {
		return x.Table
	}
	return TableName_MENU_ITEMS
}

var File_eof_message_proto protoreflect.FileDescriptor

const file_eof_message_proto_rawDesc = "" +
	"\n" +
	"\x11eof_message.proto\x12\bprotocol\x1a\x10table_data.proto\"7\n" +
	"\n" +
	"EOFMessage\x12)\n" +
	"\x05table\x18\x01 \x01(\x0e2\x13.protocol.TableNameR\x05tableB6Z4github.com/fede/coffee-shop-analyzer/protos;protocolb\x06proto3"

var (
	file_eof_message_proto_rawDescOnce sync.Once
	file_eof_message_proto_rawDescData []byte
)

func file_eof_message_proto_rawDescGZIP() []byte {
	file_eof_message_proto_rawDescOnce.Do(func() {
		file_eof_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eof_message_proto_rawDesc), len(file_eof_message_proto_rawDesc)))
	})
	return file_eof_message_proto_rawDescData
}

var file_eof_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_eof_message_proto_goTypes = []any{
	(*EOFMessage)(nil), // 0: protocol.EOFMessage
	(TableName)(0),     // 1: protocol.TableName
}
var file_eof_message_proto_depIdxs = []int32{
	1, // 0: protocol.EOFMessage.table:type_name -> protocol.TableName
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_eof_message_proto_init() }
func file_eof_message_proto_init() {
	if File_eof_message_proto != nil {
		return
	}
	file_table_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eof_message_proto_rawDesc), len(file_eof_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eof_message_proto_goTypes,
		DependencyIndexes: file_eof_message_proto_depIdxs,
		MessageInfos:      file_eof_message_proto_msgTypes,
	}.Build()
	File_eof_message_proto = out.File
	file_eof_message_proto_goTypes = nil
	file_eof_message_proto_depIdxs = nil
}
