// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: query_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryType int32

const (
	QueryType_QUERY_1 QueryType = 0 // Morning high-value transactions
	QueryType_QUERY_2 QueryType = 1 // Product ranking
	QueryType_QUERY_3 QueryType = 2 // TPV analysis
	QueryType_QUERY_4 QueryType = 3 // Top customers
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_1",
		1: "QUERY_2",
		2: "QUERY_3",
		3: "QUERY_4",
	}
	QueryType_value = map[string]int32{
		"QUERY_1": 0,
		"QUERY_2": 1,
		"QUERY_3": 2,
		"QUERY_4": 3,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_query_request_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_query_request_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_query_request_proto_rawDescGZIP(), []int{0}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryType     QueryType              `protobuf:"varint,1,opt,name=query_type,json=queryType,proto3,enum=protocol.QueryType" json:"query_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_query_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_query_request_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQueryType() QueryType {
	if x != nil {
		return x.QueryType
	}
	return QueryType_QUERY_1
}

var File_query_request_proto protoreflect.FileDescriptor

const file_query_request_proto_rawDesc = "" +
	"\n" +
	"\x13query_request.proto\x12\bprotocol\"B\n" +
	"\fQueryRequest\x122\n" +
	"\n" +
	"query_type\x18\x01 \x01(\x0e2\x13.protocol.QueryTypeR\tqueryType*?\n" +
	"\tQueryType\x12\v\n" +
	"\aQUERY_1\x10\x00\x12\v\n" +
	"\aQUERY_2\x10\x01\x12\v\n" +
	"\aQUERY_3\x10\x02\x12\v\n" +
	"\aQUERY_4\x10\x03B6Z4github.com/fede/coffee-shop-analyzer/protos;protocolb\x06proto3"

var (
	file_query_request_proto_rawDescOnce sync.Once
	file_query_request_proto_rawDescData []byte
)

func file_query_request_proto_rawDescGZIP() []byte {
	file_query_request_proto_rawDescOnce.Do(func() {
		file_query_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_request_proto_rawDesc), len(file_query_request_proto_rawDesc)))
	})
	return file_query_request_proto_rawDescData
}

var file_query_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_query_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_query_request_proto_goTypes = []any{
	(QueryType)(0),       // 0: protocol.QueryType
	(*QueryRequest)(nil), // 1: protocol.QueryRequest
}
var file_query_request_proto_depIdxs = []int32{
	0, // 0: protocol.QueryRequest.query_type:type_name -> protocol.QueryType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_query_request_proto_init() }
func file_query_request_proto_init() {
	if File_query_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_request_proto_rawDesc), len(file_query_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_request_proto_goTypes,
		DependencyIndexes: file_query_request_proto_depIdxs,
		EnumInfos:         file_query_request_proto_enumTypes,
		MessageInfos:      file_query_request_proto_msgTypes,
	}.Build()
	File_query_request_proto = out.File
	file_query_request_proto_goTypes = nil
	file_query_request_proto_depIdxs = nil
}
