// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: table_data.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableName int32

const (
	TableName_MENU_ITEMS        TableName = 0
	TableName_STORES            TableName = 1
	TableName_TRANSACTION_ITEMS TableName = 2
	TableName_TRANSACTIONS      TableName = 3
	TableName_USERS             TableName = 4
	TableName_QUERY_RESULTS_1   TableName = 5
	TableName_QUERY_RESULTS_2   TableName = 6
	TableName_QUERY_RESULTS_3   TableName = 7
	TableName_QUERY_RESULTS_4   TableName = 8
)

// Enum value maps for TableName.
var (
	TableName_name = map[int32]string{
		0: "MENU_ITEMS",
		1: "STORES",
		2: "TRANSACTION_ITEMS",
		3: "TRANSACTIONS",
		4: "USERS",
		5: "QUERY_RESULTS_1",
		6: "QUERY_RESULTS_2",
		7: "QUERY_RESULTS_3",
		8: "QUERY_RESULTS_4",
	}
	TableName_value = map[string]int32{
		"MENU_ITEMS":        0,
		"STORES":            1,
		"TRANSACTION_ITEMS": 2,
		"TRANSACTIONS":      3,
		"USERS":             4,
		"QUERY_RESULTS_1":   5,
		"QUERY_RESULTS_2":   6,
		"QUERY_RESULTS_3":   7,
		"QUERY_RESULTS_4":   8,
	}
)

func (x TableName) Enum() *TableName {
	p := new(TableName)
	*p = x
	return p
}

func (x TableName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableName) Descriptor() protoreflect.EnumDescriptor {
	return file_table_data_proto_enumTypes[0].Descriptor()
}

func (TableName) Type() protoreflect.EnumType {
	return &file_table_data_proto_enumTypes[0]
}

func (x TableName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableName.Descriptor instead.
func (TableName) EnumDescriptor() ([]byte, []int) {
	return file_table_data_proto_rawDescGZIP(), []int{0}
}

type BatchStatus int32

const (
	BatchStatus_CONTINUE BatchStatus = 0
	BatchStatus_EOF      BatchStatus = 1
	BatchStatus_CANCEL   BatchStatus = 2
)

// Enum value maps for BatchStatus.
var (
	BatchStatus_name = map[int32]string{
		0: "CONTINUE",
		1: "EOF",
		2: "CANCEL",
	}
	BatchStatus_value = map[string]int32{
		"CONTINUE": 0,
		"EOF":      1,
		"CANCEL":   2,
	}
)

func (x BatchStatus) Enum() *BatchStatus {
	p := new(BatchStatus)
	*p = x
	return p
}

func (x BatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_table_data_proto_enumTypes[1].Descriptor()
}

func (BatchStatus) Type() protoreflect.EnumType {
	return &file_table_data_proto_enumTypes[1]
}

func (x BatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatchStatus.Descriptor instead.
func (BatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_table_data_proto_rawDescGZIP(), []int{1}
}

type TableSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSchema) Reset() {
	*x = TableSchema{}
	mi := &file_table_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSchema) ProtoMessage() {}

func (x *TableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_table_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSchema.ProtoReflect.Descriptor instead.
func (*TableSchema) Descriptor() ([]byte, []int) {
	return file_table_data_proto_rawDescGZIP(), []int{0}
}

func (x *TableSchema) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_table_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_table_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_table_data_proto_rawDescGZIP(), []int{1}
}

func (x *Row) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type TableData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          TableName              `protobuf:"varint,1,opt,name=name,proto3,enum=protocol.TableName" json:"name,omitempty"`
	Schema        *TableSchema           `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	BatchNumber   uint64                 `protobuf:"varint,4,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	Status        BatchStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=protocol.BatchStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableData) Reset() {
	*x = TableData{}
	mi := &file_table_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableData) ProtoMessage() {}

func (x *TableData) ProtoReflect() protoreflect.Message {
	mi := &file_table_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableData.ProtoReflect.Descriptor instead.
func (*TableData) Descriptor() ([]byte, []int) {
	return file_table_data_proto_rawDescGZIP(), []int{2}
}

func (x *TableData) GetName() TableName {
	if x != nil {
		return x.Name
	}
	return TableName_MENU_ITEMS
}

func (x *TableData) GetSchema() *TableSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *TableData) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *TableData) GetBatchNumber() uint64 {
	if x != nil {
		return x.BatchNumber
	}
	return 0
}

func (x *TableData) GetStatus() BatchStatus {
	if x != nil {
		return x.Status
	}
	return BatchStatus_CONTINUE
}

var File_table_data_proto protoreflect.FileDescriptor

const file_table_data_proto_rawDesc = "" +
	"\n" +
	"\x10table_data.proto\x12\bprotocol\"'\n" +
	"\vTableSchema\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xd8\x01\n" +
	"\tTableData\x12'\n" +
	"\x04name\x18\x01 \x01(\x0e2\x13.protocol.TableNameR\x04name\x12-\n" +
	"\x06schema\x18\x02 \x01(\v2\x15.protocol.TableSchemaR\x06schema\x12!\n" +
	"\x04rows\x18\x03 \x03(\v2\r.protocol.RowR\x04rows\x12!\n" +
	"\fbatch_number\x18\x04 \x01(\x04R\vbatchNumber\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.protocol.BatchStatusR\x06status*\xaf\x01\n" +
	"\tTableName\x12\x0e\n" +
	"\n" +
	"MENU_ITEMS\x10\x00\x12\n" +
	"\n" +
	"\x06STORES\x10\x01\x12\x15\n" +
	"\x11TRANSACTION_ITEMS\x10\x02\x12\x10\n" +
	"\fTRANSACTIONS\x10\x03\x12\t\n" +
	"\x05USERS\x10\x04\x12\x13\n" +
	"\x0fQUERY_RESULTS_1\x10\x05\x12\x13\n" +
	"\x0fQUERY_RESULTS_2\x10\x06\x12\x13\n" +
	"\x0fQUERY_RESULTS_3\x10\a\x12\x13\n" +
	"\x0fQUERY_RESULTS_4\x10\b*0\n" +
	"\vBatchStatus\x12\f\n" +
	"\bCONTINUE\x10\x00\x12\a\n" +
	"\x03EOF\x10\x01\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x02B6Z4github.com/fede/coffee-shop-analyzer/protos;protocolb\x06proto3"

var (
	file_table_data_proto_rawDescOnce sync.Once
	file_table_data_proto_rawDescData []byte
)

func file_table_data_proto_rawDescGZIP() []byte {
	file_table_data_proto_rawDescOnce.Do(func() {
		file_table_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_table_data_proto_rawDesc), len(file_table_data_proto_rawDesc)))
	})
	return file_table_data_proto_rawDescData
}

var file_table_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_table_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_table_data_proto_goTypes = []any{
	(TableName)(0),      // 0: protocol.TableName
	(BatchStatus)(0),    // 1: protocol.BatchStatus
	(*TableSchema)(nil), // 2: protocol.TableSchema
	(*Row)(nil),         // 3: protocol.Row
	(*TableData)(nil),   // 4: protocol.TableData
}
var file_table_data_proto_depIdxs = []int32{
	0, // 0: protocol.TableData.name:type_name -> protocol.TableName
	2, // 1: protocol.TableData.schema:type_name -> protocol.TableSchema
	3, // 2: protocol.TableData.rows:type_name -> protocol.Row
	1, // 3: protocol.TableData.status:type_name -> protocol.BatchStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_table_data_proto_init() }
func file_table_data_proto_init() {
	if File_table_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_table_data_proto_rawDesc), len(file_table_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_table_data_proto_goTypes,
		DependencyIndexes: file_table_data_proto_depIdxs,
		EnumInfos:         file_table_data_proto_enumTypes,
		MessageInfos:      file_table_data_proto_msgTypes,
	}.Build()
	File_table_data_proto = out.File
	file_table_data_proto_goTypes = nil
	file_table_data_proto_depIdxs = nil
}
