# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envelope.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import databatch_pb2 as databatch__pb2
import eof_message_pb2 as eof__message__pb2
import table_data_pb2 as table__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65nvelope.proto\x12\x08protocol\x1a\x0f\x64\x61tabatch.proto\x1a\x11\x65of_message.proto\x1a\x10table_data.proto\"\xb4\x02\n\x08\x45nvelope\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.protocol.Envelope.Opcode\x12)\n\ndata_batch\x18\x02 \x01(\x0b\x32\x13.protocol.DataBatchH\x00\x12#\n\x03\x65of\x18\x03 \x01(\x0b\x32\x14.protocol.EOFMessageH\x00\x12)\n\ntable_data\x18\x04 \x01(\x0b\x32\x13.protocol.TableDataH\x00\"y\n\x06Opcode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nDATA_BATCH\x10\x01\x12\x07\n\x03\x45OF\x10\x02\x12\x0c\n\x08\x46INISHED\x10\x03\x12\x0e\n\nTABLE_DATA\x10\x04\x12\x16\n\x12\x42\x41TCH_RECV_SUCCESS\x10\x05\x12\x13\n\x0f\x42\x41TCH_RECV_FAIL\x10\x06\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=83
  _globals['_ENVELOPE']._serialized_end=391
  _globals['_ENVELOPE_OPCODE']._serialized_start=259
  _globals['_ENVELOPE_OPCODE']._serialized_end=380
# @@protoc_insertion_point(module_scope)
